name: Docker Image CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # The Twistlock user with the CI User role
  TL_USER: 003e0ae1-64a8-498c-a7e8-2415eb237d2a
  # The password for this user account
  TL_PASS: KIQ8em/dHSL/vO8lgh8BAcYmZ14=
  # The base URL for the console -- http://console.<my_company>.com:8083 -- without a trailing /
  TL_CONSOLE_URL: https://us-east1.cloud.twistlock.com/us-2-158286553

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: descarga twistcli
      run: |
        curl -k -u $TL_USER:$TL_PASS --output ./twistcli $TL_CONSOLE_URL/api/v1/util/twistcli
        # ...and ensure it's executable.
        sudo chmod a+x ./twistcli

    - name: Build the Docker image
      run: docker build -t primero .
    
    - name: Scan image
      env:
        CONTAINER_IMAGE: ${{ steps.build-image.outputs.image }}
      run: echo pasa

    - name: cuarta parte
      run: echo $CONTAINER_IMAGE.
           echo $TL_PASS.
